config/routes.rb
Rails.application.routes.draw do

  get 'settings/edit'

  get 'registrations/new'

  get 'sessions/new'
  resources :registrations, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]

  resources :items
  resources :groups
  resources :users
  resources :landings
  resources :members
  root to: "users#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :first_name, :last_name, presence: true, uniqueness: { case_sensitive: false }
  validates :screen_name, length: { maximum: 140 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password

  mount_uploader :image, ImageUploader

  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      # @current_userがnilかfalseならログインユーザーを代入
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user

  private
  def not_authenticated
    redirect_to landings_url, :alert => "ログインをお願いします。"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_login

  def index
    @item = Item.new
    @user = current_user
  end

  def show
    @item = Item.find(params[:id])
    @user = current_user
    @items = Item.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @item = Item.new(items_user)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    @user.update_attributes(params_user)
    redirect_to items_url(@user)
  end

   private

  def items_user
    params.require(:item).permit(:name, :image, :date)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    # @members = Member.all
    @user = current_user
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:user_id, :group_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    p "saiwaki"
    logger.debug @user.inspect

    if @user.save
      auto_login(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  private

  def params_user
    params.require(:user).permit(:image, :first_name, :last_name, :screen_name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    @item = Item.new
  end

  def create
    email    = params_user[:email]
    password = params_user[:password]

    if login(email, password)
      redirect_to users_url, notice: "ログインに成功しました。"
    else
      @user = User.new(email: email)
      render :new
    end
  end

    def destroy
      logout
      redirect_to landings_url, notice: "ログアウトしました。"
    end

  private

  def params_user
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(params_user)
    redirect_to user_url(@user)
  end

  private

  def params_user
    params.require(:user).permit(:last_name, :firts_name, :introduce, :image, :image_cache, :remove_image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy]
  before_filter :require_login

  def index
    @user = current_user
    @item = Item.new
  end

  def show
    @user = User.find(params[:id])
    @item = Item.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    @user.update_attributes(params_user)
    redirect_to users_url(@user)
  end

   private

  def params_user
    params.require(:user).permit(:screen_name, :self_introduce, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :introduce
    = f.text_area :introduce
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Introduce:
  = @group.introduce
%p
  %b Image:
  = @group.image

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    %br/
    = f.file_field :image
    = f.hidden_field :image_cache
  .field
    = f.label :date
    = f.date_field :date
  .actions
    = f.submit '保存'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
.container-fluid
  .row
    .col-xs-2
      .float-left
        = image_tag "Shares-logo.png"
      .profile
        %p.profile-img
          = image_tag @user.image.url
        %p.profile-name
          = link_to "#{@user.screen_name}", users_path
      .menu メニュー
      %ul.menu-ul
        %li.menu-li
          .menu-1
            %i.fa.fa-search
            %a{:href => ""} 貸し出しリスト
          / .menu-3{"data-target" => "#myModal2", "data-toggle" => "modal"}
          /   %i.fa.fa-user-plus
          /   %a{:href => "#myModal2"} 友達を招待する
          / #myModal2.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
          /   .modal-dialog
          /     .modal-content
          /       .modal-header
          /         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          /           %span{"aria-hidden" => "true"} ×
          /         %h4#myModalLabel.modal-title メールアドレスで友達を招待する。
          /       .modal-body
          /         .form
          /           %form{:action => "bbs.php", :method => "post"}
          /             %input{:name => "mode", :type => "hidden", :value => "write"}/
          /             メールアドレス：
          /             %input{:type => "text", :value => "example@gmail.com"}/
          /             .clear
          /       .modal-footer
          /         %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
          /         %button.btn.btn-primary{:type => "button"} 招待
          .menu-4{"data-target" => "#myModal4", "data-toggle" => "modal"}
            %i.fa.fa-pencil-square-o
            %a{:href => "#myModal4"} グループ編集
          #myModal4.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  %h4#myModalLabel.modal-title グループを編集する
                .modal-body
                  .form
                    %form{:action => "bbs.php", :method => "post"}
                      %input{:name => "mode", :type => "hidden", :value => "write"}/
                      グループ名：
                      %input{:type => "text-group"}/
                      %br/
                      グループ説明
                      %br/
                      %textarea{:cols => "70", :name => "group-details", :rows => "5"}
                      .clear
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  %button.btn.btn-primary{:type => "button"} 編集
          %i.fa.fa-exchange
          %a{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseExample"} グループ切替
          %ul#collapseExample.collapse
            %li
              %a{:href => ""} ・ゼミ
            %li
              %a{:href => ""} ・サークル
            %li
              %a{:href => ""} ・地元
          .menu-5{"data-target" => "#myModal3", "data-toggle" => "modal"}
            %i.fa.fa-plus-circle
            %a{:href => "#myModal3"} グループ作成
          #myModal3.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  %h4#myModalLabel.modal-title 新しいグループを作成する。
                .modal-body
                  .form
                    %form{:action => "bbs.php", :method => "post"}
                      %input{:name => "mode", :type => "hidden", :value => "write"}/
                      グループ名：
                      %input{:type => "text"}/
                      .clear
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  %button.btn.btn-primary{:type => "button"} 作成
          - if current_user
            .menu-5
              %i.fa.fa-sign-out
              / = link_to current_user.name, current_user
              = link_to "ログアウト", session_path(current_user.id), method: :delete
    .col-xs-10{:style => ""}
      .main
        .group-images-box
          .group-images
        .row
          .col-xs-9{:style => ""}
            .group-name
              %p.underline.font-weight グループ名
            .group-name 早稲田住み
            .item-add
              %button.btn.btn-primary.btn-ms{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} 貸し出しリストに追加
            #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog
                .modal-content
                  .modal-header
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                    %h4#myModalLabel.modal-title 貸し出しリストに追加する
                    = render 'form'
                  / .modal-body
                  /   .form
                  /     %form{:action => "bbs.php", :method => "post"}
                  /       %input{:name => "mode", :type => "hidden", :value => "write"}/
                  /       商品名：
                  /       %input{:type => "text"}/
                  /       %input{:type => "file", :value => "写真を添付"}/
                  /       .clear
                  / .modal-footer
                  /   %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  /   %button.btn.btn-primary{:type => "button"} 保存
            %form.navbar-form
              .form-group
                %input.form-control{:placeholder => "キーワード", :type => "text"}/
              %button.btn.btn-xs{:type => "submit"}
                %i.fa.fa-search 検索
            .line
            %p.underline 貸し出しリスト
            .item
              .item-img
              = image_tag @item.image.url
              %p.item-name
              = @item.name
              %p.name
              = current_user.screen_name
            .item
              .item-img
              = image_tag "berryz.jpg"
              %p.item-name
                %a{:href => ""} Berryz工房（写真集）
              %p.name
                %a{:href => ""} 星なな
            .item
              .item-img
              = image_tag "taro.jpg"
              %p.item-name
                %a{:href => ""} 自分の中に毒を持て
              %p.name
                %a{:href => ""} 兼清光太郎
            .item
              .item-img
              = image_tag "wear.jpg"
              %p.item-name
                %a{:href => ""} 登山用ウェア
              %p.name
                %a{:href => ""} 中村浩尚
            .item
              .item-img
              = image_tag "tako.jpg"
              %p.item-name
                %a{:href => ""} たこ焼き器
              %p.name
                %a{:href => ""} 熊谷祐
            .item
              .item-img
              = image_tag "tie.jpg"
              %p.item-name
                %a{:href => ""} ネクタイ
              %p.name
                %a{:href => ""} 中村浩尚
            .more
              %a.glyphicon.glyphicon-triangle-bottom.float-right{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#more-item-list"} さらに
              .clear
            #more-item-list.collapse
              .more-item
                .item
                  %img.item-img{:src => "assets/berryz.jpg"}/
                  %p.item-name Berryz工房（写真集）
                  %p.name 星なな
          .col-xs-3{:style => ""}
            %p.font-weight-underline グループ説明
            %p.member
            = link_to 'メンバー詳細', members_path
            %p.group-details こんにちは！管理人の熊谷です。このグループは早稲田に住んでいる人限定のグループです。
            .line
            %p.font-weight-underline 管理人
            .profile
              %p.profile-img
                = image_tag "profile.jpg"
              %p.profile-name
                %a{:href => ""} 熊谷祐
#footer
  %small Copyright Yu Kumagai 2015 Shares. All rights reserved.

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
.container-fluid
  .row
    .col-xs-2
      .float-left
        = image_tag "Shares-logo.png"
      .profile
        %p.profile-img
          = image_tag @user.image.url
        %p.profile-name
          = link_to "#{@user.screen_name}", user_path
      .menu メニュー
      %ul.menu-ul
        %li.menu-li
          .menu-1
            %i.fa.fa-search
            %a{:href => ""} 貸し出しリスト
          / .menu-3{"data-target" => "#myModal2", "data-toggle" => "modal"}
          /   %i.fa.fa-user-plus
          /   %a{:href => "#myModal2"} 友達を招待する
          / #myModal2.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
          /   .modal-dialog
          /     .modal-content
          /       .modal-header
          /         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          /           %span{"aria-hidden" => "true"} ×
          /         %h4#myModalLabel.modal-title メールアドレスで友達を招待する。
          /       .modal-body
          /         .form
          /           %form{:action => "bbs.php", :method => "post"}
          /             %input{:name => "mode", :type => "hidden", :value => "write"}/
          /             メールアドレス：
          /             %input{:type => "text", :value => "example@gmail.com"}/
          /             .clear
          /       .modal-footer
          /         %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
          /         %button.btn.btn-primary{:type => "button"} 招待
          .menu-4{"data-target" => "#myModal4", "data-toggle" => "modal"}
            %i.fa.fa-pencil-square-o
            %a{:href => "#myModal4"} グループ編集
          #myModal4.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  %h4#myModalLabel.modal-title グループを編集する
                .modal-body
                  .form
                    %form{:action => "bbs.php", :method => "post"}
                      %input{:name => "mode", :type => "hidden", :value => "write"}/
                      グループ名：
                      %input{:type => "text-group"}/
                      %br/
                      グループ説明
                      %br/
                      %textarea{:cols => "70", :name => "group-details", :rows => "5"}
                      .clear
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  %button.btn.btn-primary{:type => "button"} 編集
          %i.fa.fa-exchange
          %a{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseExample"} グループ切替
          %ul#collapseExample.collapse
            %li
              %a{:href => ""} ・ゼミ
            %li
              %a{:href => ""} ・サークル
            %li
              %a{:href => ""} ・地元
          .menu-5{"data-target" => "#myModal3", "data-toggle" => "modal"}
            %i.fa.fa-plus-circle
            %a{:href => "#myModal3"} グループ作成
          #myModal3.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  %h4#myModalLabel.modal-title 新しいグループを作成する。
                .modal-body
                  .form
                    %form{:action => "bbs.php", :method => "post"}
                      %input{:name => "mode", :type => "hidden", :value => "write"}/
                      グループ名：
                      %input{:type => "text"}/
                      .clear
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  %button.btn.btn-primary{:type => "button"} 作成
          - if current_user
            .menu-5
              %i.fa.fa-sign-out
              / = link_to current_user.name, current_user
              = link_to "ログアウト", session_path(current_user.id), method: :delete
    .col-xs-10{:style => ""}
      .main
        .group-images-box
          .group-images
        .row
          .col-xs-9{:style => ""}
            .group-name
              %p.underline.font-weight グループ名
            .group-name 早稲田住み
            .item-add
              %button.btn.btn-primary.btn-ms{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} 貸し出しリストに追加
            #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog
                .modal-content
                  .modal-header
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                    %h4#myModalLabel.modal-title 貸し出しリストに追加する
                    = render 'form'
                  / .modal-body
                  /   .form
                  /     %form{:action => "bbs.php", :method => "post"}
                  /       %input{:name => "mode", :type => "hidden", :value => "write"}/
                  /       商品名：
                  /       %input{:type => "text"}/
                  /       %input{:type => "file", :value => "写真を添付"}/
                  /       .clear
                  / .modal-footer
                  /   %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 中止
                  /   %button.btn.btn-primary{:type => "button"} 保存
            %form.navbar-form
              .form-group
                %input.form-control{:placeholder => "キーワード", :type => "text"}/
              %button.btn.btn-xs{:type => "submit"}
                %i.fa.fa-search 検索
            .line
            %p.underline 貸し出しリスト
            .item
              .item-img
              = image_tag @item.image.url
              %p.item-name
                = @item.name
              %p.name
                = @user.screen_name
            .item
              .item-img
              = image_tag "berryz.jpg"
              %p.item-name
                %a{:href => ""} Berryz工房（写真集）
              %p.name
                %a{:href => ""} 星なな
            .item
              .item-img
              = image_tag "taro.jpg"
              %p.item-name
                %a{:href => ""} 自分の中に毒を持て
              %p.name
                %a{:href => ""} 兼清光太郎
            .item
              .item-img
              = image_tag "wear.jpg"
              %p.item-name
                %a{:href => ""} 登山用ウェア
              %p.name
                %a{:href => ""} 中村浩尚
            .item
              .item-img
              = image_tag "tako.jpg"
              %p.item-name
                %a{:href => ""} たこ焼き器
              %p.name
                %a{:href => ""} 熊谷祐
            .item
              .item-img
              = image_tag "tie.jpg"
              %p.item-name
                %a{:href => ""} ネクタイ
              %p.name
                %a{:href => ""} 中村浩尚
            .more
              %a.glyphicon.glyphicon-triangle-bottom.float-right{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#more-item-list"} さらに
              .clear
            #more-item-list.collapse
              .more-item
                .item
                  %img.item-img{:src => "assets/berryz.jpg"}/
                  %p.item-name Berryz工房（写真集）
                  %p.name 星なな
          .col-xs-3{:style => ""}
            %p.font-weight-underline グループ説明
            %p.member
            = link_to 'メンバー詳細', members_path
            %p.group-details こんにちは！管理人の熊谷です。このグループは早稲田に住んでいる人限定のグループです。
            .line
            %p.font-weight-underline 管理人
            .profile
              %p.profile-img
                = image_tag "profile.jpg"
              %p.profile-name
                %a{:href => ""} 熊谷祐
#footer
  %small Copyright Yu Kumagai 2015 Shares. All rights reserved.



/ %p#notice= 貸し出しリストに追加

/ %p
/   %b 商品名:
/   = @item.name
/ %p
/   %b 画像:
/   = @item.image
/ %p
/   %b 日にち:
/   = @item.date

/ = link_to 'Edit', edit_item_path(@item)
/ \|
/ = link_to 'Back', items_path

app/views/landings/index.html.haml
#page
  %header
    %nav
      .float-left
        .logo
          = image_tag "Shares-logo.png"
      .float-right
        %ul
          / %li
          /   %a{:href => ""}
          /     %img{:alt => "facebook", :src => "assets/facebook.png"}/
          %li
            = link_to new_session_path do
              マイページ
              %i.fa.fa-sign-in
          %li
            = link_to registrations_new_path do
              会員登録
              %i.fa.fa-user
%div{:align => "center"}
  .main-image
    = image_tag "top2.png"
#main
  %div{:align => "center"}
    %h1 サービス説明
    %p
      Sharesは、
      %strong> グループ内で気軽に貸し借りができるサービス
      です。
    %p １年に数回しか使わないたこ焼き器、アクセサリー、間接照明など、
    %p
      %strong> 「買うほどじゃないけど、あったらいいな」
      というモノから、
    %p 調味料や食器、ドライヤーなどの日常生活品まで
    %p 生活の様々な場面で貸し借りをして、生活を豊かにしてみてはどうでしょうか。
    %h2 使い方
  .howto-content
    %ul.howto
      %li ①会員登録をする
      %li ②グループに加入（作成）する。
      %li ③貸し出しリストに貸せるものを追加。
      %li ④借りたいものを選択し、持ち主にメッセージ
  %h3.line
  %ul.introduce
    %li
      %a{:href => ""} 作成者
    %li
      %a{:href => ""} ブログ
  %footer
    %small Copyright Yu Kumagai 2015 Shares. All rights reserved.

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :group_id
    = f.number_field :group_id
  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice

%p
  %b User:
  = @member.user_id
%p
  %b Group:
  = @member.group_id

= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path

app/views/settings/edit.html.haml
%h1 Settings#edit
%p Find me in app/views/settings/edit.html.haml

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  .field
    ニックネーム
    %br/
    = f.text_field :screen_name
  .field
    自己紹介
    %br/
    = f.text_area :self_introduce
  / 追加箇所 開始
  .field
    - if @user.image?
      .thumbnail
        = image_tag @user.image.url
    %br/
    = f.label :image
    %br/
    = f.file_field :image
    = f.hidden_field :image_cache
  .field
    / 既存レコード(DBに保存されている)かつ、画像が存在する場合
    - if @user.persisted? && @user.image?
      %label
        = f.check_box :remove_image
        画像を削除
  / 追加箇所 終了
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path